#include "conf/keyconf.h"

const SDL_Scancode NEXT_SCENE_KEY = SDL_SCANCODE_RETURN;
const SDL_Scancode ABOVE_SCENE_KEY = SDL_SCANCODE_ESCAPE;
const SDL_Scancode PAUSE_KEY = SDL_SCANCODE_SPACE;
const SDL_Scancode LEFT_KEY = SDL_SCANCODE_A;
const SDL_Scancode RIGHT_KEY = SDL_SCANCODE_D;
const SDL_Scancode UP_KEY = SDL_SCANCODE_W;
const SDL_Scancode DOWN_KEY = SDL_SCANCODE_S;
const SDL_Scancode LEFT_ROTATE_KEY = SDL_SCANCODE_J;
const SDL_Scancode RIGHT_ROTATE_KEY = SDL_SCANCODE_L;